---
title: "Etapa1"
author: "Alys Jiménez"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(printr)

setwd("/Users/alysjime/Downloads")
getwd()
datos_2024 <- read.csv("Datos_molec_2024-1.csv", na.strings = c("", "NA"))

str(datos_2024) #Muestra la estructura de la base de datos
names(datos_2024) #Muestra la lista de nombres de las variables
head(datos_2024) #Muestra las primeras 6 filas
View(datos_2024) #Muestra los datos en una nueva pestaña
print(dim(datos_2024))
summary(datos_2024) #Revisa si hay datos faltantes

#Número de encuestas por estado
estados_n_2024 <- datos_2024 %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2024)

#Número de encuestas por género
sexo_n_2024 <- datos_2024 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2024)

#Por nivel educativo
datos_2024 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2024 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  #Variables demográficas
  "entidad", 
  "sexo", 
  "edad", 
  "nivel",
  
  #Variables de las preguntas sobre hábitos de lectura
  "p1", #¿Sabe leer y escribir un recado?
  "p2", #¿Acostumbra leer?
  "p4", #¿Cuántos libros leyó en los últimos doce meses?
  "p10", #¿Cuántas revistas leyó en los últimos tres meses?
  "p16", #¿Cuántos periódicos leyó la semana pasada?
  "p22", #¿Acostumbra leer historietas?
  "p3_5", #¿Lee páginas de Internet, foros o blogs?
  "p26", #¿Minutos continuos que lee?
  "p31", #¿Consulta otros materiales para más información?
  "p33_3", #¿Asistió a una biblioteca?
  "p33_4", #¿Asistió a una librería?
  "p34_1" #De niño(a), ¿lo llevaban a bibliotecas o librerías?
)

df_final_2024 <- datos_2024 %>%
select(all_of(variables_seleccionadas))
print(head(df_final_2024))

valores_faltantes = colSums(is.na(df_final_2024))

porcentaje_faltantes = (valores_faltantes / nrow(df_final_2024)) * 100

reporte = data.frame(
  Variable = names(porcentaje_faltantes),
  Porcentaje_Faltantes = porcentaje_faltantes
)

reporte_final <- reporte %>%
print(reporte_final)
```


```{r}

datos_2023 <- read.csv("Datos_molec_2023-1.csv")

str(datos_2023) #Muestra la estructura de la base de datos
names(datos_2023) #Muestra la lista de nombres de las variables
head(datos_2023) #Muestra las primeras 6 filas
View(datos_2023) #Muestra los datos en una nueva pestaña
print(dim(datos_2023))
summary(datos_2023) #Revisa si hay datos faltantes 


#Número de encuestas por estado
estados_n_2023 <- datos_2023 %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2023)

#Número de encuestas por género
sexo_n_2023 <- datos_2023 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2023)

#Por nivel educativo
datos_2023 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2023 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  "entidad", "sexo", "edad", "nivel", "p1", "p2", "p4", "p10", 
  "p16", "p22", "p3_5", "p26", "p31", "p33_3", "p33_4", "p34_1"
)

#Data frame
df_final_2023 <- datos_2023 %>%
  select(all_of(variables_seleccionadas))
print(head(df_final_2023))

#Calcular el porcentaje de datos faltantes
valores_faltantes_2023 <- colSums(is.na(df_final_2023))
porcentaje_faltantes_2023 <- (valores_faltantes_2023 / nrow(df_final_2023)) * 100

#Crear el dataframe con el reporte
reporte_2023 <- data.frame(
  Variable = names(porcentaje_faltantes_2023),
  Porcentaje_Faltantes = porcentaje_faltantes_2023
)

print(reporte_2023)
```

```{r}

datos_2022 <- read.csv("Datos_molec_2022-1.csv")

str(datos_2022) #Muestra la estructura de la base de datos
names(datos_2022) #Muestra la lista de nombres de las variables
head(datos_2022) #Muestra las primeras 6 filas
View(datos_2022) #Muestra los datos en una nueva pestaña
print(dim(datos_2022))
summary(datos_2022) #Revisa si hay datos faltantes 


#Número de encuestas por estado
estados_n_2022 <- datos_2022 %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2022)

#Número de encuestas por género
sexo_n_2022 <- datos_2022 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2022)

#Por nivel educativo
datos_2022 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2022 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  "entidad", "sexo", "edad", "nivel", "p1", "p2", "p4", "p10", 
  "p16", "p22", "p3_5", "p26", "p31", "p33_3", "p33_4", "p34_1"
)

#Data frame
df_final_2022 <- datos_2022 %>%
  select(all_of(variables_seleccionadas))
print(head(df_final_2022))

#Calcular el porcentaje de datos faltantes
valores_faltantes_2022 <- colSums(is.na(df_final_2022))
porcentaje_faltantes_2022 <- (valores_faltantes_2022 / nrow(df_final_2022)) * 100

#Crear el dataframe con el reporte
reporte_2022 <- data.frame(
  Variable = names(porcentaje_faltantes_2022),
  Porcentaje_Faltantes = porcentaje_faltantes_2022
)

print(reporte_2022)
```


```{r}

datos_2021 <- read.csv("Datos_molec_2021-1.csv")

str(datos_2021) #Muestra la estructura de la base de datos
names(datos_2021) #Muestra la lista de nombres de las variables
head(datos_2021) #Muestra las primeras 6 filas
View(datos_2021) #Muestra los datos en una nueva pestaña
print(dim(datos_2021))
summary(datos_2021) #Revisa si hay datos faltantes 


#Número de encuestas por estado
estados_n_2021 <- datos_2021 %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2021)

#Número de encuestas por género
sexo_n_2021 <- datos_2021 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2021)

#Por nivel educativo
datos_2021 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2021 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  "entidad", "sexo", "edad", "nivel", "p1", "p2", "p4", "p10", 
  "p16", "p22", "p3_5", "p26", "p31", "p33_3", "p33_4", "p34_1"
)

#Data frame
df_final_2021 <- datos_2021 %>%
  select(all_of(variables_seleccionadas))
print(head(df_final_2021))

#Calcular el porcentaje de datos faltantes
valores_faltantes_2021 <- colSums(is.na(df_final_2021))
porcentaje_faltantes_2021 <- (valores_faltantes_2021 / nrow(df_final_2021)) * 100

#Crear el dataframe con el reporte
reporte_2021 <- data.frame(
  Variable = names(porcentaje_faltantes_2021),
  Porcentaje_Faltantes = porcentaje_faltantes_2021
)

print(reporte_2021)
```
```{r}

datos_2020 <- read.csv("Datos_molec_2020-1.csv")

str(datos_2020) #Muestra la estructura de la base de datos
names(datos_2020) #Muestra la lista de nombres de las variables
head(datos_2020) #Muestra las primeras 6 filas
View(datos_2020) #Muestra los datos en una nueva pestaña
print(dim(datos_2020) )
summary(datos_2020) #Revisa si hay datos faltantes 


#Número de encuestas por estado
estados_n_2020 <- (datos_2020)  %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2020)

#Número de encuestas por género
sexo_n_2020 <- datos_2020 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2020)

#Por nivel educativo
datos_2020 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2020 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  "entidad", "sexo", "edad", "nivel", "p1", "p2", "p4", "p10", 
  "p16", "p22", "p3_5", "p26", "p31", "p33_3", "p33_4", "p34_1"
)

#Data frame
df_final_2020 <- datos_2020 %>%
  select(all_of(variables_seleccionadas))
print(head(df_final_2020))

#Calcular el porcentaje de datos faltantes
valores_faltantes_2020 <- colSums(is.na(df_final_2020))
porcentaje_faltantes_2020 <- (valores_faltantes_2020 / nrow(df_final_2020)) * 100

#Crear el dataframe con el reporte
reporte_2020 <- data.frame(
  Variable = names(porcentaje_faltantes_2020),
  Porcentaje_Faltantes = porcentaje_faltantes_2020
)

print(reporte_2020)
```


```{r}

datos_2019 <- read.csv("Datos_molec_2019-1.csv")

str(datos_2019) #Muestra la estructura de la base de datos
names(datos_2019) #Muestra la lista de nombres de las variables
head(datos_2019) #Muestra las primeras 6 filas
View(datos_2019) #Muestra los datos en una nueva pestaña
print(dim(datos_2019))
summary(datos_2019) #Revisa si hay datos faltantes 


#Número de encuestas por estado
estados_n_2019 <- (datos_2019)  %>% 
  group_by(entidad) %>% 
  summarize(numero = n())
print(estados_n_2019)

#Número de encuestas por género
sexo_n_2019 <- datos_2019 %>% 
  group_by(sexo) %>% 
  summarize(numero = n())
print(sexo_n_2019)

#Por nivel educativo
datos_2019 %>%
  count(nivel) %>%
  arrange(desc(n))

#Conteo por edad
datos_2019 %>%
  count(edad) %>%
  arrange(edad)

variables_seleccionadas <- c(
  "entidad", "sexo", "edad", "nivel", "p1", "p2", "p4", "p10", 
  "p16", "p22", "p3_5", "p26", "p31", "p33_3", "p33_4", "p34_1"
)

#Data frame
df_final_2019 <- datos_2019 %>%
  select(all_of(variables_seleccionadas))
print(head(df_final_2019))

#Calcular el porcentaje de datos faltantes
valores_faltantes_2019 <- colSums(is.na(df_final_2019))
porcentaje_faltantes_2019 <- (valores_faltantes_2019 / nrow(df_final_2019)) * 100

#Crear el dataframe con el reporte
reporte_2019 <- data.frame(
  Variable = names(porcentaje_faltantes_2019),
  Porcentaje_Faltantes = porcentaje_faltantes_2019
)

print(reporte_2019)
```
